### ISSUE TITLE
字体长度超出省略号

### ISSUE THREAD

**Issue by wenyejie** [wenyejie/blog#10]
```css
.text-ellipsis {
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
```
