### ISSUE TITLE
CSS3禁止用户选中文本

### ISSUE THREAD

**Issue by wenyejie** [wenyejie/blog#13]
```css
.demo {
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```
