### ISSUE TITLE
css3 三角形

### ISSUE THREAD

**Issue by wenyejie** [wenyejie/blog#14]
```css
.demo {
  width: 0;
  height: 0;
  border-left: .08rem solid transparent;
  border-right: .08rem solid transparent;
  border-top: .14rem solid rgba(255, 5, 49, 0.70);
}
```
