### ISSUE TITLE
移除input type="number"的上下箭头

### ISSUE THREAD

**Issue by wenyejie** [wenyejie/blog#15]
```css
input[type="number"]::-webkit-inner-spin-button,
input[type="number"]::-webkit-outer-spin-button {
  -webkit-appearance: none;
}
input[type='number'] {
  -moz-appearance: textfield;
}
```
