### ISSUE TITLE
多行省略

### ISSUE THREAD

**Issue by wenyejie** [wenyejie/blog#27]
```css
.demo {
  width: 400px;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
```
