### ISSUE TITLE
隐藏滚动条样式

### ISSUE THREAD

**Issue by wenyejie** [wenyejie/blog#35]
```css
html::-webkit-scrollbar {
      display: none;
    }
    html {
      -ms-overflow-style: none;
    }
```
