### ISSUE TITLE
父元素矩形, 子元素为正方形

### ISSUE THREAD

**Issue by wenyejie** [wenyejie/blog#61]
```html
<div class="parent">
    <div class="child"></div>
</div>
```
```css
.parent {
    width: 200px;
    height: 400px;
    background-color: red;
    display: flex;
}
.child {
    width: 100%;
    margin-bottom: 50%;
    margin-top: 50%;
    background-color: yellow;

}
```
