### ISSUE TITLE
矩形/缺角矩形

### ISSUE THREAD

**Issue by wenyejie** [wenyejie/blog#65]
```css
.demo {
  width: 200px;
  height: 150px;
  background: linear-gradient(135deg, transparent 70px, #999 0 );
  filter: drop-shadow(1px 1px 8px #d9d9d9);
}
```

![screenshot-20230911-164853](https://github.com/wenyejie/blog/assets/4539115/b7a41b77-dde1-4b29-912c-bc6f4d014531)
![screenshot-20230911-164955](https://github.com/wenyejie/blog/assets/4539115/cd700521-db5c-4b36-9d7e-5b400a10848c)

也可以通过`clip-path`来实现
```css
.demo {
  clip-path: polygon(23% 0, 100% 0, 100% 99%, 0 100%, 0% 38%);
}
```
