### ISSUE TITLE
渐变色边框

### ISSUE THREAD

**Issue by wenyejie** [wenyejie/blog#67]
```css
.border {
  position: relative;
  border: 2px solid transparent;
  border-radius: 10px;
  background: linear-gradient(134deg, #EEEEFF 0%, #F4F6FF 44%, #ECEDFF 100%);
  background-clip: padding-box;
  padding: 15px 22px 20px 22px;
  /* just to show box-shadow still works fine */
  box-shadow: 0 2px 4px 0 rgba(174, 174, 174, 0.5);
}

.border::after {
  position: absolute;
  top: -2px;
  bottom: -2px;
  left: -2px;
  right: -2px;
  background: linear-gradient(
    138deg,
    rgba(184, 55, 255, 1),
    rgba(97, 112, 255, 1),
    rgba(211, 90, 255, 1),
    rgba(86, 129, 255, 1)
  );

  content: "";
  z-index: -1;
  border-radius: 10px;
}
```
