### ISSUE TITLE
环形进度条

### ISSUE THREAD

**Issue by wenyejie** [wenyejie/blog#68]
```css
@property --percent {
  syntax: '<angle>';
  inherits: false;
  initial-value: 0deg;
}
.loading {
  position: relative;
  width: 100px;
  height: 100px;
  background-clip: padding-box;
  background-color: #fff;
  border: 2px solid transparent;
  border-radius: 50%;
}
.loading::before {
  border-radius: 50%;
  content: "";
  position: absolute;
  left: -2px;
  right: -2px;
  bottom: -2px;
  top: -2px;
  z-index: -1;
  background: conic-gradient(#9557FF 0deg, #9557FF var(--percent), #fff var(--percent), #fff 360deg);
  animation: loading 10s linear infinite;
  /* transition: --percent .3s linear; */
}
@keyframes loading {
  0% {
    --percent: 0deg;
  }
  100% {
    --percent: 360deg;
  }
}
```
